// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SomeTests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Asdf - Use 'AsdfParams' to pass parameters into this method.
        /// </summary>
        public void Asdf()
        {
            #region Variable Declarations
            WinComboBox uIItemComboBox = this.UIMozillaFirefoxStartPWindow.UINavigationToolbarToolBar.UIItemComboBox;
            WinEdit uISearchorenteraddressEdit = this.UIMozillaFirefoxStartPWindow.UIItemComboBox.UISearchorenteraddressEdit;
            WinControl uIQshusgameDocument = this.UIMozillaFirefoxStartPWindow.UIItemPropertyPage.UIQshusgameDocument;
            WinEdit uIPlayEdit = this.UIMozillaFirefoxStartPWindow.UIQshusgameDocument.UIPlayEdit;
            WinButton uIOpenanewtabButton = this.UIMozillaFirefoxStartPWindow.UIItemTabList.UIOpenanewtabButton;
            WinCustom uIItemCustom = this.UIMozillaFirefoxStartPWindow.UIQshusgameDocument.UIItemCustom;
            WinTabPage uIQshusgameTabPage = this.UIMozillaFirefoxStartPWindow.UIItemTabList.UIQshusgameTabPage;
            WinCustom uIItemCustom1 = this.UIMozillaFirefoxStartPWindow.UIQshusgameDocument.UIItemCustom1;
            WinTabPage uIQshusgameTabPage1 = this.UIMozillaFirefoxStartPWindow.UIItemTabList.UIQshusgameTabPage1;
            #endregion

            // Launch 'D:\Programs\firefox\firefox.exe'
            ApplicationUnderTest uIMozillaFirefoxStartPWindow = ApplicationUnderTest.Launch(this.AsdfParams.UIMozillaFirefoxStartPWindowExePath, this.AsdfParams.UIMozillaFirefoxStartPWindowAlternateExePath);

            // Select 'http://localhost:6494/Gun/index.html' in combo box
            uIItemComboBox.EditableItem = this.AsdfParams.UIItemComboBoxEditableItem;

            // Type '{Enter}' in 'Search or enter address' text box
            Keyboard.SendKeys(uISearchorenteraddressEdit, this.AsdfParams.UISearchorenteraddressEditSendKeys, ModifierKeys.None);

            // Click 'Qshu's game' document
            Mouse.Click(uIQshusgameDocument, new Point(469, 183));

            // Click 'Play' text box
            Mouse.Click(uIPlayEdit, new Point(19, 1));

            // Click 'Open a new tab' button
            Mouse.Click(uIOpenanewtabButton, new Point(17, 12));

            // Select 'http://localhost:6494/Gun/index.html' in combo box
            uIItemComboBox.EditableItem = this.AsdfParams.UIItemComboBoxEditableItem1;

            // Type '{Enter}' in 'Search or enter address' text box
            Keyboard.SendKeys(uISearchorenteraddressEdit, this.AsdfParams.UISearchorenteraddressEditSendKeys1, ModifierKeys.None);

            // Click custom control
            Mouse.Click(uIItemCustom, new Point(16, 37));

            // Click 'Qshu's game' tab
            Mouse.Click(uIQshusgameTabPage, new Point(152, 10));

            // Move custom control numbered 3 in 'Qshu's game' document
            Mouse.StartDragging(uIItemCustom1, new Point(208, 103));
            Mouse.StopDragging(uIItemCustom1, 201, 149);

            // Click 'Qshu's game' tab
            Mouse.Click(uIQshusgameTabPage1, new Point(98, 16));

            // Move custom control numbered 3 in 'Qshu's game' document
            Mouse.StartDragging(uIItemCustom1, new Point(420, 109));
            Mouse.StopDragging(uIItemCustom1, -283, 137);
        }
        
        /// <summary>
        /// Asdfasdf - Use 'AsdfasdfParams' to pass parameters into this method.
        /// </summary>
        public void Asdfasdf()
        {
            #region Variable Declarations
            WinComboBox uIItemComboBox = this.UIMozillaFirefoxStartPWindow.UINavigationToolbarToolBar.UIItemComboBox;
            WinEdit uISearchorenteraddressEdit = this.UIMozillaFirefoxStartPWindow.UIItemComboBox.UISearchorenteraddressEdit;
            WinControl uIQshusgameDocument = this.UIMozillaFirefoxStartPWindow.UIItemPropertyPage.UIQshusgameDocument;
            WinEdit uIPlayEdit = this.UIMozillaFirefoxStartPWindow.UIQshusgameDocument.UIPlayEdit;
            WinTabPage uIQshusgameTabPage1 = this.UIMozillaFirefoxStartPWindow.UIItemTabList.UIQshusgameTabPage1;
            WinCustom uIItemCustom1 = this.UIMozillaFirefoxStartPWindow.UIQshusgameDocument.UIItemCustom1;
            WinTabPage uIQshusgameTabPage = this.UIMozillaFirefoxStartPWindow.UIItemTabList.UIQshusgameTabPage;
            #endregion

            // Launch 'D:\Programs\firefox\firefox.exe'
            ApplicationUnderTest uIMozillaFirefoxStartPWindow = ApplicationUnderTest.Launch(this.AsdfasdfParams.UIMozillaFirefoxStartPWindowExePath, this.AsdfasdfParams.UIMozillaFirefoxStartPWindowAlternateExePath);

            // Select 'http://localhost:6494/Gun/index.html' in combo box
            uIItemComboBox.EditableItem = this.AsdfasdfParams.UIItemComboBoxEditableItem;

            // Type '{Enter}' in 'Search or enter address' text box
            Keyboard.SendKeys(uISearchorenteraddressEdit, this.AsdfasdfParams.UISearchorenteraddressEditSendKeys, ModifierKeys.None);

            // Type 'Control + t' in 'Qshu's game' document
            Keyboard.SendKeys(uIQshusgameDocument, this.AsdfasdfParams.UIQshusgameDocumentSendKeys, ModifierKeys.Control);

            // Type 'Control + v' in 'Qshu's game' document
            Keyboard.SendKeys(uIQshusgameDocument, this.AsdfasdfParams.UIQshusgameDocumentSendKeys1, ModifierKeys.Control);

            // Type '{Enter}' in 'Search or enter address' text box
            Keyboard.SendKeys(uISearchorenteraddressEdit, this.AsdfasdfParams.UISearchorenteraddressEditSendKeys1, ModifierKeys.None);

            // Type 'Control, Shift + {Tab}' in 'Qshu's game' document
            Keyboard.SendKeys(uIQshusgameDocument, this.AsdfasdfParams.UIQshusgameDocumentSendKeys2, (ModifierKeys.Control | ModifierKeys.Shift));

            // Move 'Qshu's game' document
            Mouse.StartDragging(uIQshusgameDocument, new Point(1141, 175));
            Mouse.StopDragging(uIQshusgameDocument, 165, 65);

            // Double-Click 'Qshu's game' document
            Mouse.DoubleClick(uIQshusgameDocument, new Point(1020, 203));

            // Click 'Play' text box
            Mouse.Click(uIPlayEdit, new Point(1, 15));

            // Click 'Qshu's game' tab
            Mouse.Click(uIQshusgameTabPage1, new Point(47, 14));

            // Click 'Play' text box
            Mouse.Click(uIPlayEdit, new Point(3, 4));

            // Move custom control numbered 3 in 'Qshu's game' document
            Mouse.StartDragging(uIItemCustom1, new Point(934, 122));
            Mouse.StopDragging(uIItemCustom1, -632, 350);

            // Move custom control numbered 3 in 'Qshu's game' document
            Mouse.StartDragging(uIItemCustom1, new Point(302, 472));
            Mouse.StopDragging(uIItemCustom1, 347, -160);

            // Move custom control numbered 3 in 'Qshu's game' document
            Mouse.StartDragging(uIItemCustom1, new Point(533, 339));
            Mouse.StopDragging(uIItemCustom1, -70, -74);

            // Click 'Qshu's game' tab
            Mouse.Click(uIQshusgameTabPage, new Point(168, 6));

            // Move custom control numbered 3 in 'Qshu's game' document
            Mouse.StartDragging(uIItemCustom1, new Point(418, 204));
            Mouse.StopDragging(uIItemCustom1, 324, 314);

            // Move custom control numbered 3 in 'Qshu's game' document
            Mouse.StartDragging(uIItemCustom1, new Point(505, 419));
            Mouse.StopDragging(uIItemCustom1, -20, -87);
        }
        
        #region Properties
        public virtual AsdfParams AsdfParams
        {
            get
            {
                if ((this.mAsdfParams == null))
                {
                    this.mAsdfParams = new AsdfParams();
                }
                return this.mAsdfParams;
            }
        }
        
        public virtual AsdfasdfParams AsdfasdfParams
        {
            get
            {
                if ((this.mAsdfasdfParams == null))
                {
                    this.mAsdfasdfParams = new AsdfasdfParams();
                }
                return this.mAsdfasdfParams;
            }
        }
        
        public UIMozillaFirefoxStartPWindow UIMozillaFirefoxStartPWindow
        {
            get
            {
                if ((this.mUIMozillaFirefoxStartPWindow == null))
                {
                    this.mUIMozillaFirefoxStartPWindow = new UIMozillaFirefoxStartPWindow();
                }
                return this.mUIMozillaFirefoxStartPWindow;
            }
        }
        #endregion
        
        #region Fields
        private AsdfParams mAsdfParams;
        
        private AsdfasdfParams mAsdfasdfParams;
        
        private UIMozillaFirefoxStartPWindow mUIMozillaFirefoxStartPWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Asdf'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class AsdfParams
    {
        
        #region Fields
        /// <summary>
        /// Launch 'D:\Programs\firefox\firefox.exe'
        /// </summary>
        public string UIMozillaFirefoxStartPWindowExePath = "D:\\Programs\\firefox\\firefox.exe";
        
        /// <summary>
        /// Launch 'D:\Programs\firefox\firefox.exe'
        /// </summary>
        public string UIMozillaFirefoxStartPWindowAlternateExePath = "D:\\Programs\\firefox\\firefox.exe";
        
        /// <summary>
        /// Select 'http://localhost:6494/Gun/index.html' in combo box
        /// </summary>
        public string UIItemComboBoxEditableItem = "http://localhost:6494/Gun/index.html";
        
        /// <summary>
        /// Type '{Enter}' in 'Search or enter address' text box
        /// </summary>
        public string UISearchorenteraddressEditSendKeys = "{Enter}";
        
        /// <summary>
        /// Select 'http://localhost:6494/Gun/index.html' in combo box
        /// </summary>
        public string UIItemComboBoxEditableItem1 = "http://localhost:6494/Gun/index.html";
        
        /// <summary>
        /// Type '{Enter}' in 'Search or enter address' text box
        /// </summary>
        public string UISearchorenteraddressEditSendKeys1 = "{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Asdfasdf'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class AsdfasdfParams
    {
        
        #region Fields
        /// <summary>
        /// Launch 'D:\Programs\firefox\firefox.exe'
        /// </summary>
        public string UIMozillaFirefoxStartPWindowExePath = "D:\\Programs\\firefox\\firefox.exe";
        
        /// <summary>
        /// Launch 'D:\Programs\firefox\firefox.exe'
        /// </summary>
        public string UIMozillaFirefoxStartPWindowAlternateExePath = "D:\\Programs\\firefox\\firefox.exe";
        
        /// <summary>
        /// Select 'http://localhost:6494/Gun/index.html' in combo box
        /// </summary>
        public string UIItemComboBoxEditableItem = "http://localhost:6494/Gun/index.html";
        
        /// <summary>
        /// Type '{Enter}' in 'Search or enter address' text box
        /// </summary>
        public string UISearchorenteraddressEditSendKeys = "{Enter}";
        
        /// <summary>
        /// Type 'Control + t' in 'Qshu's game' document
        /// </summary>
        public string UIQshusgameDocumentSendKeys = "t";
        
        /// <summary>
        /// Type 'Control + v' in 'Qshu's game' document
        /// </summary>
        public string UIQshusgameDocumentSendKeys1 = "v";
        
        /// <summary>
        /// Type '{Enter}' in 'Search or enter address' text box
        /// </summary>
        public string UISearchorenteraddressEditSendKeys1 = "{Enter}";
        
        /// <summary>
        /// Type 'Control, Shift + {Tab}' in 'Qshu's game' document
        /// </summary>
        public string UIQshusgameDocumentSendKeys2 = "{Tab}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIMozillaFirefoxStartPWindow : WinWindow
    {
        
        public UIMozillaFirefoxStartPWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Mozilla Firefox Start Page - Mozilla Firefox";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MozillaWindowClass";
            this.WindowTitles.Add("Mozilla Firefox Start Page - Mozilla Firefox");
            this.WindowTitles.Add("Mozilla Firefox");
            this.WindowTitles.Add("Qshu\'s game - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public UINavigationToolbarToolBar UINavigationToolbarToolBar
        {
            get
            {
                if ((this.mUINavigationToolbarToolBar == null))
                {
                    this.mUINavigationToolbarToolBar = new UINavigationToolbarToolBar(this);
                }
                return this.mUINavigationToolbarToolBar;
            }
        }
        
        public UIItemComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new UIItemComboBox(this);
                }
                return this.mUIItemComboBox;
            }
        }
        
        public UIItemPropertyPage UIItemPropertyPage
        {
            get
            {
                if ((this.mUIItemPropertyPage == null))
                {
                    this.mUIItemPropertyPage = new UIItemPropertyPage(this);
                }
                return this.mUIItemPropertyPage;
            }
        }
        
        public UIQshusgameDocument UIQshusgameDocument
        {
            get
            {
                if ((this.mUIQshusgameDocument == null))
                {
                    this.mUIQshusgameDocument = new UIQshusgameDocument(this);
                }
                return this.mUIQshusgameDocument;
            }
        }
        
        public UIItemTabList UIItemTabList
        {
            get
            {
                if ((this.mUIItemTabList == null))
                {
                    this.mUIItemTabList = new UIItemTabList(this);
                }
                return this.mUIItemTabList;
            }
        }
        #endregion
        
        #region Fields
        private UINavigationToolbarToolBar mUINavigationToolbarToolBar;
        
        private UIItemComboBox mUIItemComboBox;
        
        private UIItemPropertyPage mUIItemPropertyPage;
        
        private UIQshusgameDocument mUIQshusgameDocument;
        
        private UIItemTabList mUIItemTabList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UINavigationToolbarToolBar : WinToolBar
    {
        
        public UINavigationToolbarToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Navigation Toolbar";
            this.WindowTitles.Add("Mozilla Firefox Start Page - Mozilla Firefox");
            this.WindowTitles.Add("Mozilla Firefox");
            this.WindowTitles.Add("Qshu\'s game - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIItemComboBox.WindowTitles.Add("Mozilla Firefox Start Page - Mozilla Firefox");
                    this.mUIItemComboBox.WindowTitles.Add("Mozilla Firefox");
                    this.mUIItemComboBox.WindowTitles.Add("Qshu\'s game - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIItemComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIItemComboBox : WinComboBox
    {
        
        public UIItemComboBox(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Mozilla Firefox Start Page - Mozilla Firefox");
            this.WindowTitles.Add("Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UISearchorenteraddressEdit
        {
            get
            {
                if ((this.mUISearchorenteraddressEdit == null))
                {
                    this.mUISearchorenteraddressEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUISearchorenteraddressEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Search or enter address";
                    this.mUISearchorenteraddressEdit.WindowTitles.Add("Mozilla Firefox Start Page - Mozilla Firefox");
                    this.mUISearchorenteraddressEdit.WindowTitles.Add("Mozilla Firefox");
                    #endregion
                }
                return this.mUISearchorenteraddressEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUISearchorenteraddressEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIItemPropertyPage : WinControl
    {
        
        public UIItemPropertyPage(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "PropertyPage";
            this.WindowTitles.Add("Qshu\'s game - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinControl UIQshusgameDocument
        {
            get
            {
                if ((this.mUIQshusgameDocument == null))
                {
                    this.mUIQshusgameDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIQshusgameDocument.SearchProperties[UITestControl.PropertyNames.Name] = "Qshu\'s game";
                    this.mUIQshusgameDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIQshusgameDocument.WindowTitles.Add("Qshu\'s game - Mozilla Firefox");
                    #endregion
                }
                return this.mUIQshusgameDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIQshusgameDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIQshusgameDocument : WinControl
    {
        
        public UIQshusgameDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Qshu\'s game";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Qshu\'s game - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIPlayEdit
        {
            get
            {
                if ((this.mUIPlayEdit == null))
                {
                    this.mUIPlayEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIPlayEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Play";
                    this.mUIPlayEdit.WindowTitles.Add("Qshu\'s game - Mozilla Firefox");
                    #endregion
                }
                return this.mUIPlayEdit;
            }
        }
        
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.WindowTitles.Add("Qshu\'s game - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public WinCustom UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom1.SearchProperties["Instance"] = "3";
                    this.mUIItemCustom1.WindowTitles.Add("Qshu\'s game - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemCustom1;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIPlayEdit;
        
        private WinCustom mUIItemCustom;
        
        private WinCustom mUIItemCustom1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIItemTabList : WinTabList
    {
        
        public UIItemTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Qshu\'s game - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinButton UIOpenanewtabButton
        {
            get
            {
                if ((this.mUIOpenanewtabButton == null))
                {
                    this.mUIOpenanewtabButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOpenanewtabButton.SearchProperties[WinButton.PropertyNames.Name] = "Open a new tab";
                    this.mUIOpenanewtabButton.WindowTitles.Add("Qshu\'s game - Mozilla Firefox");
                    #endregion
                }
                return this.mUIOpenanewtabButton;
            }
        }
        
        public WinTabPage UIQshusgameTabPage
        {
            get
            {
                if ((this.mUIQshusgameTabPage == null))
                {
                    this.mUIQshusgameTabPage = new WinTabPage(this);
                    #region Search Criteria
                    this.mUIQshusgameTabPage.SearchProperties[WinTabPage.PropertyNames.Name] = "Qshu\'s game";
                    this.mUIQshusgameTabPage.WindowTitles.Add("Qshu\'s game - Mozilla Firefox");
                    #endregion
                }
                return this.mUIQshusgameTabPage;
            }
        }
        
        public WinTabPage UIQshusgameTabPage1
        {
            get
            {
                if ((this.mUIQshusgameTabPage1 == null))
                {
                    this.mUIQshusgameTabPage1 = new WinTabPage(this);
                    #region Search Criteria
                    this.mUIQshusgameTabPage1.SearchProperties[WinTabPage.PropertyNames.Name] = "Qshu\'s game";
                    this.mUIQshusgameTabPage1.SearchProperties[WinTabPage.PropertyNames.Instance] = "2";
                    this.mUIQshusgameTabPage1.WindowTitles.Add("Qshu\'s game - Mozilla Firefox");
                    #endregion
                }
                return this.mUIQshusgameTabPage1;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOpenanewtabButton;
        
        private WinTabPage mUIQshusgameTabPage;
        
        private WinTabPage mUIQshusgameTabPage1;
        #endregion
    }
}
